export const LLAMAFILE = "llamafile";
export const OPENAI = "openai";
export const ANTHROPIC = "anthropic";
export const MISTRAL = "mistral";
export const GOOGLE = "google";
export const MODELDEPLOYER = "modeldeployer";
export const OLLAMA = "ollama";
export const GROQ = "groq";
export const SERVICES = [LLAMAFILE, OPENAI, ANTHROPIC, MISTRAL, GOOGLE, MODELDEPLOYER, OLLAMA, GROQ];
